
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ahate
 */
public class CheckingTrip extends javax.swing.JFrame {
int x=0;
private void EnableNext()
{
     
        if(x==5)jBtnNext.setEnabled(true);
}
    /**
     * Creates new form CheckingTrip
     */
    public CheckingTrip() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtDisplay = new javax.swing.JTextField();
        jBtn7 = new javax.swing.JButton();
        jBtn8 = new javax.swing.JButton();
        jBtn9 = new javax.swing.JButton();
        jBtn4 = new javax.swing.JButton();
        jBtn5 = new javax.swing.JButton();
        jBtn6 = new javax.swing.JButton();
        jBtn3 = new javax.swing.JButton();
        jBtn1 = new javax.swing.JButton();
        jBtn2 = new javax.swing.JButton();
        jBtnC = new javax.swing.JButton();
        jBtnNext = new javax.swing.JButton();
        jBtn0 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Enter ticket number :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(6, 31, 217, 51);

        jtxtDisplay.setEnabled(false);
        jtxtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDisplayActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtDisplay);
        jtxtDisplay.setBounds(80, 110, 270, 34);

        jBtn7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtn7.setText("7");
        jBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn7ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn7);
        jBtn7.setBounds(66, 171, 63, 40);

        jBtn8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtn8.setText("8");
        jBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn8ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn8);
        jBtn8.setBounds(172, 171, 63, 40);

        jBtn9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtn9.setText("9");
        jBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn9ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn9);
        jBtn9.setBounds(273, 171, 63, 40);

        jBtn4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtn4.setText("4");
        jBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn4ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn4);
        jBtn4.setBounds(66, 237, 63, 40);

        jBtn5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtn5.setText("5");
        jBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn5ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn5);
        jBtn5.setBounds(172, 237, 63, 40);

        jBtn6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtn6.setText("6");
        jBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn6ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn6);
        jBtn6.setBounds(273, 237, 63, 40);

        jBtn3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtn3.setText("3");
        jBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn3ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn3);
        jBtn3.setBounds(273, 295, 63, 40);

        jBtn1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtn1.setText("1");
        jBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn1);
        jBtn1.setBounds(66, 295, 63, 40);

        jBtn2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtn2.setText("2");
        jBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn2);
        jBtn2.setBounds(172, 295, 63, 40);

        jBtnC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtnC.setText("C");
        jBtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnC);
        jBtnC.setBounds(208, 353, 128, 40);

        jBtnNext.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtnNext.setText("Next");
        jBtnNext.setEnabled(false);
        jBtnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNextActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnNext);
        jBtnNext.setBounds(66, 399, 128, 40);

        jBtn0.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtn0.setText("0");
        jBtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn0ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn0);
        jBtn0.setBounds(66, 353, 136, 40);

        jButton1.setText("Check");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(212, 406, 124, 28);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp_pc\\Desktop\\Webp.net-resizeimage (5).jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-100, -30, 520, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn4ActionPerformed
  String Number = jtxtDisplay.getText() + jBtn4.getText();
        jtxtDisplay.setText(Number);    }//GEN-LAST:event_jBtn4ActionPerformed

    private void jBtnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNextActionPerformed
           
        if(x>5)
        {
            Toolkit.getDefaultToolkit().beep();
            String warning = "Ticket number consists of 5 digits only.";
            JOptionPane.showMessageDialog(null, warning);
            jtxtDisplay.setText("");
            x=0;
        }
        else if (x==5)
        {
            
            BookDetails tripD = new BookDetails();
            tripD.setVisible(true);
            this.setVisible(false);
            x=0;
        }
    }//GEN-LAST:event_jBtnNextActionPerformed

    private void jtxtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDisplayActionPerformed

    private void jBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn9ActionPerformed
        EnableNext();
        String Number = jtxtDisplay.getText() + jBtn9.getText();
        jtxtDisplay.setText(Number);
        x++;
    }//GEN-LAST:event_jBtn9ActionPerformed

    private void jBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn8ActionPerformed
        EnableNext();
        String Number = jtxtDisplay.getText() + jBtn8.getText();
        x++;
        jtxtDisplay.setText(Number);    }//GEN-LAST:event_jBtn8ActionPerformed

    private void jBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn7ActionPerformed
        EnableNext();
        x++;
        String Number = jtxtDisplay.getText() + jBtn7.getText();
        jtxtDisplay.setText(Number);    }//GEN-LAST:event_jBtn7ActionPerformed

    private void jBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn6ActionPerformed
 EnableNext();  
 x++;
        String Number = jtxtDisplay.getText() + jBtn6.getText();
        jtxtDisplay.setText(Number);    }//GEN-LAST:event_jBtn6ActionPerformed

    private void jBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn5ActionPerformed
        EnableNext();
        x++;
        String Number = jtxtDisplay.getText() + jBtn5.getText();
        jtxtDisplay.setText(Number);    }//GEN-LAST:event_jBtn5ActionPerformed

    private void jBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn3ActionPerformed
        EnableNext();
        x++;
        String Number = jtxtDisplay.getText() + jBtn3.getText();
        jtxtDisplay.setText(Number);    }//GEN-LAST:event_jBtn3ActionPerformed

    private void jBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn2ActionPerformed
        EnableNext();
        x++;
        String Number = jtxtDisplay.getText() + jBtn2.getText();
        jtxtDisplay.setText(Number);    }//GEN-LAST:event_jBtn2ActionPerformed

    private void jBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn1ActionPerformed
        EnableNext();
        x++;
        String Number = jtxtDisplay.getText() + jBtn1.getText();
        jtxtDisplay.setText(Number);    }//GEN-LAST:event_jBtn1ActionPerformed

    private void jBtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn0ActionPerformed
        EnableNext();
        x++;
        String Number = jtxtDisplay.getText() + jBtn0.getText();
        jtxtDisplay.setText(Number);    }//GEN-LAST:event_jBtn0ActionPerformed

    private void jBtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCActionPerformed
        x--;
        if(x==0)jBtnC.setEnabled(false);
        int length = jtxtDisplay.getText().length();
        int n = jtxtDisplay.getText().length() - 1;
        String storing;

        if (length > 0) {
            StringBuilder back = new StringBuilder(jtxtDisplay.getText());
            back.deleteCharAt(n);
            storing = back.toString();
            jtxtDisplay.setText(storing);
        }
    }//GEN-LAST:event_jBtnCActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  if(x>5)
        {
            Toolkit.getDefaultToolkit().beep();
            String warning = "Ticket number consists of 5 digits only.";
            JOptionPane.showMessageDialog(null, warning);
            jtxtDisplay.setText("");
            x=0;
        }
         if (x==5)
        {
            jBtnNext.setEnabled(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckingTrip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckingTrip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckingTrip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckingTrip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckingTrip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn0;
    private javax.swing.JButton jBtn1;
    private javax.swing.JButton jBtn2;
    private javax.swing.JButton jBtn3;
    private javax.swing.JButton jBtn4;
    private javax.swing.JButton jBtn5;
    private javax.swing.JButton jBtn6;
    private javax.swing.JButton jBtn7;
    private javax.swing.JButton jBtn8;
    private javax.swing.JButton jBtn9;
    private javax.swing.JButton jBtnC;
    private javax.swing.JButton jBtnNext;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jtxtDisplay;
    // End of variables declaration//GEN-END:variables
}
