/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp_pc
 */
public class ReserveChairWindow extends javax.swing.JFrame {

    /**
     * Creates new form ReserveChairWindow
     */
    public ReserveChairWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        s28 = new javax.swing.JButton();
        s27 = new javax.swing.JButton();
        s32 = new javax.swing.JButton();
        s31 = new javax.swing.JButton();
        s5 = new javax.swing.JButton();
        s6 = new javax.swing.JButton();
        s12 = new javax.swing.JButton();
        s11 = new javax.swing.JButton();
        s9 = new javax.swing.JButton();
        s10 = new javax.swing.JButton();
        s16 = new javax.swing.JButton();
        s15 = new javax.swing.JButton();
        s13 = new javax.swing.JButton();
        s14 = new javax.swing.JButton();
        s20 = new javax.swing.JButton();
        s19 = new javax.swing.JButton();
        s17 = new javax.swing.JButton();
        s18 = new javax.swing.JButton();
        s24 = new javax.swing.JButton();
        s23 = new javax.swing.JButton();
        s21 = new javax.swing.JButton();
        s22 = new javax.swing.JButton();
        s25 = new javax.swing.JButton();
        s26 = new javax.swing.JButton();
        s29 = new javax.swing.JButton();
        s30 = new javax.swing.JButton();
        s33 = new javax.swing.JButton();
        s34 = new javax.swing.JButton();
        s37 = new javax.swing.JButton();
        s38 = new javax.swing.JButton();
        s46 = new javax.swing.JButton();
        s45 = new javax.swing.JButton();
        s41 = new javax.swing.JButton();
        s42 = new javax.swing.JButton();
        s49 = new javax.swing.JButton();
        s48 = new javax.swing.JButton();
        s47 = new javax.swing.JButton();
        s36 = new javax.swing.JButton();
        s35 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        s40 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        s39 = new javax.swing.JButton();
        s4 = new javax.swing.JButton();
        s44 = new javax.swing.JButton();
        s3 = new javax.swing.JButton();
        s43 = new javax.swing.JButton();
        s1 = new javax.swing.JButton();
        s2 = new javax.swing.JButton();
        s8 = new javax.swing.JButton();
        s7 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        s28.setText("28");
        getContentPane().add(s28, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 66, -1, 33));

        s27.setText("27");
        getContentPane().add(s27, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 105, -1, 33));

        s32.setText("32");
        getContentPane().add(s32, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 66, -1, 33));

        s31.setText("31");
        getContentPane().add(s31, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 105, -1, 33));

        s5.setText("5");
        getContentPane().add(s5, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 249, -1, 33));

        s6.setText("6");
        getContentPane().add(s6, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 210, -1, 33));

        s12.setText("12");
        getContentPane().add(s12, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 66, -1, 33));

        s11.setText("11");
        getContentPane().add(s11, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 105, -1, 33));

        s9.setText("9");
        getContentPane().add(s9, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 249, 45, 33));

        s10.setText("10");
        getContentPane().add(s10, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 210, -1, 33));

        s16.setText("16");
        getContentPane().add(s16, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 66, -1, 33));

        s15.setText("15");
        getContentPane().add(s15, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 105, -1, 33));

        s13.setText("13");
        getContentPane().add(s13, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 249, -1, 33));

        s14.setText("14");
        getContentPane().add(s14, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 210, -1, 33));

        s20.setText("20");
        getContentPane().add(s20, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 66, -1, 33));

        s19.setText("19");
        getContentPane().add(s19, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 105, -1, 33));

        s17.setText("17");
        getContentPane().add(s17, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 249, -1, 33));

        s18.setText("18");
        getContentPane().add(s18, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 210, -1, 33));

        s24.setText("24");
        getContentPane().add(s24, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 210, -1, 33));

        s23.setText("23");
        getContentPane().add(s23, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 249, -1, 33));

        s21.setText("21");
        getContentPane().add(s21, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 249, -1, 33));

        s22.setText("22");
        getContentPane().add(s22, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 210, -1, 33));

        s25.setText("25");
        getContentPane().add(s25, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 249, -1, 33));

        s26.setText("26");
        getContentPane().add(s26, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 210, -1, 33));

        s29.setText("29");
        getContentPane().add(s29, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 249, -1, 33));

        s30.setText("30");
        getContentPane().add(s30, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 210, -1, 33));

        s33.setText("33");
        getContentPane().add(s33, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 249, -1, 33));

        s34.setText("34");
        getContentPane().add(s34, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 210, -1, 33));

        s37.setText("37");
        getContentPane().add(s37, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 249, -1, 33));

        s38.setText("38");
        getContentPane().add(s38, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 210, -1, 33));

        s46.setText("46");
        getContentPane().add(s46, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 210, -1, 33));

        s45.setText("45");
        getContentPane().add(s45, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 249, -1, 33));

        s41.setText("41");
        getContentPane().add(s41, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 249, -1, 33));

        s42.setText("42");
        getContentPane().add(s42, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, -1, 33));

        s49.setText("49");
        getContentPane().add(s49, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 66, -1, 33));

        s48.setText("48");
        getContentPane().add(s48, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 105, -1, 33));

        s47.setText("47");
        getContentPane().add(s47, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 159, -1, 33));

        s36.setText("36");
        getContentPane().add(s36, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 66, -1, 33));

        s35.setText("35");
        getContentPane().add(s35, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 105, -1, 33));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Please select a valid chair :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 22, 196, 33));

        s40.setText("40");
        getContentPane().add(s40, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 66, -1, 33));

        jButton1.setText("D");
        jButton1.setEnabled(false);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 210, -1, 33));

        s39.setText("39");
        getContentPane().add(s39, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 105, -1, 33));

        s4.setText("4");
        s4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s4ActionPerformed(evt);
            }
        });
        getContentPane().add(s4, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 66, -1, 33));

        s44.setText("44");
        getContentPane().add(s44, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 66, -1, 33));

        s3.setText("3");
        getContentPane().add(s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 105, -1, 33));

        s43.setText("43");
        getContentPane().add(s43, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 105, -1, 33));

        s1.setText("1");
        getContentPane().add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 249, -1, 33));

        s2.setText("2");
        s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2ActionPerformed(evt);
            }
        });
        getContentPane().add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 210, -1, 33));

        s8.setText("8");
        getContentPane().add(s8, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 66, -1, 33));

        s7.setText("7");
        getContentPane().add(s7, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 105, -1, 33));

        jButton51.setText("Next");
        jButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton51ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton51, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 22, 140, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s2ActionPerformed

    private void jButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton51ActionPerformed
        this.setVisible(false);
        BookDetails tripdet =new BookDetails();
        tripdet.setVisible(true);

    }//GEN-LAST:event_jButton51ActionPerformed

    private void s4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReserveChairWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReserveChairWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReserveChairWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReserveChairWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReserveChairWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton51;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton s1;
    private javax.swing.JButton s10;
    private javax.swing.JButton s11;
    private javax.swing.JButton s12;
    private javax.swing.JButton s13;
    private javax.swing.JButton s14;
    private javax.swing.JButton s15;
    private javax.swing.JButton s16;
    private javax.swing.JButton s17;
    private javax.swing.JButton s18;
    private javax.swing.JButton s19;
    private javax.swing.JButton s2;
    private javax.swing.JButton s20;
    private javax.swing.JButton s21;
    private javax.swing.JButton s22;
    private javax.swing.JButton s23;
    private javax.swing.JButton s24;
    private javax.swing.JButton s25;
    private javax.swing.JButton s26;
    private javax.swing.JButton s27;
    private javax.swing.JButton s28;
    private javax.swing.JButton s29;
    private javax.swing.JButton s3;
    private javax.swing.JButton s30;
    private javax.swing.JButton s31;
    private javax.swing.JButton s32;
    private javax.swing.JButton s33;
    private javax.swing.JButton s34;
    private javax.swing.JButton s35;
    private javax.swing.JButton s36;
    private javax.swing.JButton s37;
    private javax.swing.JButton s38;
    private javax.swing.JButton s39;
    private javax.swing.JButton s4;
    private javax.swing.JButton s40;
    private javax.swing.JButton s41;
    private javax.swing.JButton s42;
    private javax.swing.JButton s43;
    private javax.swing.JButton s44;
    private javax.swing.JButton s45;
    private javax.swing.JButton s46;
    private javax.swing.JButton s47;
    private javax.swing.JButton s48;
    private javax.swing.JButton s49;
    private javax.swing.JButton s5;
    private javax.swing.JButton s6;
    private javax.swing.JButton s7;
    private javax.swing.JButton s8;
    private javax.swing.JButton s9;
    // End of variables declaration//GEN-END:variables
}
